version: '3'
services:
  backend:
    build: .
    container_name: backend
    command: bash -c "cd ../ && alembic upgrade head && cd src/ && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - "./src:/src"
      - "./requirements:/requirements"
      - "./alembic:/alembic"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:13.4"
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 3s
      retries: 30
