version: '3'
services:
  backend:
    build: .
    container_name: backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - "./src:/src"
      - "./requirements:/requirements"
      - "./alembic:/alembic"
  db:
    image: "postgres:13.4"
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"

volumes:
    backend:
