"""First migration - adding Article

Revision ID: b19a91a8178e
Revises:
Create Date: 2023-08-16 03:03:24.332021

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b19a91a8178e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'article',
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('tokenized_content', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
